### ISSUE TITLE
Keycloak roles and services under roles

### ISSUE THREAD

**Issue by viachaslau-latushkin** [3scale/APIcast#1476]
Hi Dear 3scale!

I am using 3scale apicast as api-getway - combining a lot of microservices and keycloak's token validation. Also configured validation for access to endpoints of each microservice according special roles from keycloak's token.

Right now each endpoint for each role covered by next lines
```
- methods:
  - GET
    resource_type: plain
    resource: ENDPOINT
  client_roles:
    - name: ROLE_FROM_KEYCLOAK_TOKEN
        client_type: plain
        client: KEYCLOAK_ROLE
        name_type: plain
```

3scale policies.yaml extremely big in this case.
Is there any way to combine each endpoint from each microservice under list of roles without duplicating line above?
Thank you in advance for any help.
