### ISSUE TITLE
SSL issues with new apicast

### ISSUE THREAD

**Issue by 4integration** [3scale/apicast#787]
I just upgraded to latest APIcast in Docker using this image
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/3scale-amp22/apicast-gateway

To configure SSL I have followed this example
https://github.com/3scale/apicast/tree/master/examples/add-ssl
but with the new version it have been changed and the directory `/opt/app-root/src/` doesn't exist anymore in the image.

What is the new directory to be mapped?

Starting with docker-compose

```
version: '2'

services:
    gateway:
        container_name: production-qa-apicast-oauth2
        image: registry.access.redhat.com/3scale-amp22/apicast-gateway:1.8
        env_file: .env
        restart: always
        ports:
            - 90:8090
            - 443:8443
        volumes:
            - /etc/apicast.d/production:/opt/app-root/src/apicast.d:ro
            - /etc/pki/tls/certs:/opt/app-root/src/conf/cert:ro
        network_mode: "bridge"
        depends_on:
            - redis

    redis:
        container_name: production-qa-redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        network_mode: "bridge"
```
and this config
```
listen 8443 ssl;
ssl_certificate cert/star.domain.com2015-2019.crt;
ssl_certificate_key cert/star.domain.com2015-2019.key;
```
